services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: document_management_systems
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
volumes:
  mysql_data:

